apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: delivery
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: delivery-api:latest
          imagePullPolicy: Never    # utilise l'image locale (pas de registry)
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: delivery-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"